<div class="col-sm-12" style="background-color:blue; height: 50px; text-align: center; margin-top: auto; color: white;"><h1>RESULTS</h1></div>
<br>
<div class="col-lg-12">
    <div class="card">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table no-margin">
                	<tr>																							
                      	<td>Total Credit</td>
                        <td><span id="tbox2"> </span></td>
					</tr>
                    <tr>
                        <td>Earned Grade Point</td>
                        <td><span id="tbox1"></span></td>
					</tr>
					<tr>
                        <td>CGPA</td>
                        <td><span id="tbox3"></span></td>
					</tr>
				</table>
			</div>
		</div>
	</div>
</div>